// Stabilize navigation routes
com.tunjid.treenav.strings.Route

// stabilize state producing classes from mutator library
com.tunjid.mutator.ActionStateMutator
com.tunjid.mutator.coroutines.ActionSuspendingStateMutator

// stabilize immutable lists from tiling
com.tunjid.tiler.TiledList

// stabilize all classes in core data package
com.tunjid.heron.data.core.*

// stabilize ml classes
com.tunjid.heron.data.ml.engine.EngineState
com.tunjid.heron.data.ml.model.InferenceModel
com.tunjid.heron.data.ml.model.LoadedModel

// stabilize task classes
com.tunjid.heron.data.tasks.Task
com.tunjid.heron.data.tasks.TaskStatus

// Consider certain kotlin APIs stable
kotlin.CharSequence
kotlin.collections.*

// Consider kotlinx.datetime models stable
kotlinx.datetime.DayOfWeek
kotlin.time.Instant
kotlinx.datetime.LocalDate
kotlinx.datetime.LocalDateTime
kotlinx.datetime.LocalTime
kotlinx.datetime.TimeZone
kotlin.time.Duration

kotlinx.coroutines.CoroutineScope

coil3.compose.AsyncImagePainter.State
